### ISSUE TITLE
Add CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by danielgruesso** [coti-io/coti-sdk-python-examples#3]
This public repository should contain contribution guidelines so that developers can add details, examples, and instructions.

Create a CONTRIBUTING.md policy

**Comment by gmesika-coti** [comment]
@danielgruesso kindly do same as in https://github.com/coti-io/coti-sdk-typescript-examples/pull/8

**Comment by danielgruesso** [comment]
@gmesika-coti see https://github.com/coti-io/coti-sdk-python-examples/pull/11
